const lesson = (world, order, word, pronunciation, meaning, example, translation, emoji) => ({ id:`path-${world.toLowerCase().replace(/[^a-z]+/g,'-')}-${order}`, type:'pathLesson', world, order, word, pronunciation, meaning, example, translation, emoji });

export const PATH_LESSONS = [
  ['Basic Greetings',1,'Hello','/həˈləʊ/','halo','Hello, I’m Arif.','Halo, saya Arif.','👋'],
  ['Basic Greetings',2,'Good morning','/ɡʊd ˈmɔː.nɪŋ/','selamat pagi','Good morning, everyone.','Selamat pagi, semuanya.','🌤️'],
  ['Basic Greetings',3,'Good afternoon','/ɡʊd ˌɑːf.təˈnuːn/','selamat siang','Good afternoon, Ms. Rina.','Selamat siang, Bu Rina.','☀️'],
  ['Basic Greetings',4,'Good evening','/ɡʊd ˈiːv.nɪŋ/','selamat malam (saat bertemu)','Good evening. Welcome in.','Selamat malam. Silakan masuk.','🌆'],
  ['Basic Greetings',5,'Goodbye','/ˌɡʊdˈbaɪ/','selamat tinggal','Goodbye. Have a safe trip.','Selamat tinggal. Semoga perjalananmu aman.','🚪'],
  ['Basic Greetings',6,'See you later','/siː juː ˈleɪ.tər/','sampai jumpa nanti','See you later at the café.','Sampai jumpa nanti di kafe.','☕'],
  ['Basic Greetings',7,'How are you?','/haʊ ɑː juː/','apa kabar?','Hi, Dita. How are you?','Hai, Dita. Apa kabar?','🙂'],
  ['Basic Greetings',8,'I’m fine','/aɪm faɪn/','saya baik','I’m fine, thank you.','Saya baik, terima kasih.','✨'],
  ['Basic Greetings',9,'Nice to meet you','/naɪs tə miːt juː/','senang bertemu denganmu','Nice to meet you, Budi.','Senang bertemu denganmu, Budi.','🤝'],
  ['Basic Greetings',10,'Please','/pliːz/','tolong / silakan','Please sit here.','Silakan duduk di sini.','🪑'],
  ['Basic Greetings',11,'Thank you','/ˈθæŋk juː/','terima kasih','Thank you for your help.','Terima kasih atas bantuanmu.','💛'],
  ['Basic Greetings',12,'You’re welcome','/jɔː ˈwel.kəm/','sama-sama','You’re welcome. Anytime.','Sama-sama. Kapan saja.','🌟'],
  ['Family',1,'Mother','/ˈmʌð.ər/','ibu','My mother loves gardening.','Ibu saya suka berkebun.','👩'],
  ['Family',2,'Father','/ˈfɑː.ðər/','ayah','My father makes breakfast.','Ayah saya membuat sarapan.','👨'],
  ['Family',3,'Parents','/ˈpeə.rənts/','orang tua','My parents live in Surabaya.','Orang tua saya tinggal di Surabaya.','👪'],
  ['Family',4,'Sister','/ˈsɪs.tər/','saudara perempuan','My sister studies architecture.','Saudara perempuan saya belajar arsitektur.','👧'],
  ['Family',5,'Brother','/ˈbrʌð.ər/','saudara laki-laki','My brother plays football.','Saudara laki-laki saya bermain sepak bola.','👦'],
  ['Family',6,'Sibling','/ˈsɪb.lɪŋ/','saudara kandung','I have one sibling.','Saya punya satu saudara kandung.','🧑‍🤝‍🧑'],
  ['Family',7,'Grandmother','/ˈɡræn.mʌð.ər/','nenek','My grandmother tells great stories.','Nenek saya bercerita dengan baik.','👵'],
  ['Family',8,'Grandfather','/ˈɡræn.fɑː.ðər/','kakek','My grandfather walks every morning.','Kakek saya berjalan setiap pagi.','👴'],
  ['Family',9,'Aunt','/ɑːnt/','bibi','My aunt works at a hospital.','Bibi saya bekerja di rumah sakit.','🩺'],
  ['Family',10,'Uncle','/ˈʌŋ.kəl/','paman','My uncle lives nearby.','Paman saya tinggal dekat sini.','🏠'],
  ['Family',11,'Cousin','/ˈkʌz.ən/','sepupu','My cousin is the same age as me.','Sepupu saya seumuran dengan saya.','🧑'],
  ['Family',12,'Child','/tʃaɪld/','anak','Their child is five years old.','Anak mereka berusia lima tahun.','🧒'],
  ['Food',1,'Rice','/raɪs/','nasi','We eat rice for lunch.','Kami makan nasi untuk makan siang.','🍚'],
  ['Food',2,'Bread','/bred/','roti','This bread is fresh.','Roti ini segar.','🍞'],
  ['Food',3,'Vegetable','/ˈvedʒ.tə.bəl/','sayuran','Carrots are vegetables.','Wortel adalah sayuran.','🥕'],
  ['Food',4,'Fruit','/fruːt/','buah','Mango is my favorite fruit.','Mangga adalah buah favorit saya.','🥭'],
  ['Food',5,'Chicken','/ˈtʃɪk.ɪn/','ayam','I ordered grilled chicken.','Saya memesan ayam panggang.','🍗'],
  ['Food',6,'Fish','/fɪʃ/','ikan','The fish is spicy.','Ikan ini pedas.','🐟'],
  ['Food',7,'Soup','/suːp/','sup','The soup is still hot.','Supnya masih panas.','🍲'],
  ['Food',8,'Breakfast','/ˈbrek.fəst/','sarapan','Breakfast starts at seven.','Sarapan dimulai pukul tujuh.','🥣'],
  ['Food',9,'Lunch','/lʌntʃ/','makan siang','Let’s have lunch together.','Ayo makan siang bersama.','🍱'],
  ['Food',10,'Dinner','/ˈdɪn.ər/','makan malam','Dinner is ready.','Makan malam sudah siap.','🍽️'],
].map(args => lesson(...args));
