const lesson = (world, order, word, pronunciation, meaning, example, translation, emoji) => ({ id:`path-${world.toLowerCase().replace(/[^a-z]+/g,'-')}-${order}`, type:'pathLesson', world, order, word, pronunciation, meaning, example, translation, emoji });

export const PATH_LESSONS = [
  ['Basic Greetings',1,'Hello','/həˈləʊ/','halo','Hello, I’m Arif.','Halo, saya Arif.','👋'],
  ['Basic Greetings',2,'Good morning','/ɡʊd ˈmɔː.nɪŋ/','selamat pagi','Good morning, everyone.','Selamat pagi, semuanya.','🌤️'],
  ['Basic Greetings',3,'Good afternoon','/ɡʊd ˌɑːf.təˈnuːn/','selamat siang','Good afternoon, Ms. Rina.','Selamat siang, Bu Rina.','☀️'],
  ['Basic Greetings',4,'Good evening','/ɡʊd ˈiːv.nɪŋ/','selamat malam (saat bertemu)','Good evening. Welcome in.','Selamat malam. Silakan masuk.','🌆'],
  ['Basic Greetings',5,'Goodbye','/ˌɡʊdˈbaɪ/','selamat tinggal','Goodbye. Have a safe trip.','Selamat tinggal. Semoga perjalananmu aman.','🚪'],
  ['Basic Greetings',6,'See you later','/siː juː ˈleɪ.tər/','sampai jumpa nanti','See you later at the café.','Sampai jumpa nanti di kafe.','☕'],
  ['Basic Greetings',7,'How are you?','/haʊ ɑː juː/','apa kabar?','Hi, Dita. How are you?','Hai, Dita. Apa kabar?','🙂'],
  ['Basic Greetings',8,'I’m fine','/aɪm faɪn/','saya baik','I’m fine, thank you.','Saya baik, terima kasih.','✨'],
  ['Basic Greetings',9,'Nice to meet you','/naɪs tə miːt juː/','senang bertemu denganmu','Nice to meet you, Budi.','Senang bertemu denganmu, Budi.','🤝'],
  ['Basic Greetings',10,'Please','/pliːz/','tolong / silakan','Please sit here.','Silakan duduk di sini.','🪑'],
  ['Basic Greetings',11,'Thank you','/ˈθæŋk juː/','terima kasih','Thank you for your help.','Terima kasih atas bantuanmu.','💛'],
  ['Basic Greetings',12,'You’re welcome','/jɔː ˈwel.kəm/','sama-sama','You’re welcome. Anytime.','Sama-sama. Kapan saja.','🌟'],
  ['Family',1,'Mother','/ˈmʌð.ər/','ibu','My mother loves gardening.','Ibu saya suka berkebun.','👩'],
  ['Family',2,'Father','/ˈfɑː.ðər/','ayah','My father makes breakfast.','Ayah saya membuat sarapan.','👨'],
  ['Family',3,'Parents','/ˈpeə.rənts/','orang tua','My parents live in Surabaya.','Orang tua saya tinggal di Surabaya.','👪'],
  ['Family',4,'Sister','/ˈsɪs.tər/','saudara perempuan','My sister studies architecture.','Saudara perempuan saya belajar arsitektur.','👧'],
  ['Family',5,'Brother','/ˈbrʌð.ər/','saudara laki-laki','My brother plays football.','Saudara laki-laki saya bermain sepak bola.','👦'],
  ['Family',6,'Sibling','/ˈsɪb.lɪŋ/','saudara kandung','I have one sibling.','Saya punya satu saudara kandung.','🧑‍🤝‍🧑'],
  ['Family',7,'Grandmother','/ˈɡræn.mʌð.ər/','nenek','My grandmother tells great stories.','Nenek saya bercerita dengan baik.','👵'],
  ['Family',8,'Grandfather','/ˈɡræn.fɑː.ðər/','kakek','My grandfather walks every morning.','Kakek saya berjalan setiap pagi.','👴'],
  ['Family',9,'Aunt','/ɑːnt/','bibi','My aunt works at a hospital.','Bibi saya bekerja di rumah sakit.','🩺'],
  ['Family',10,'Uncle','/ˈʌŋ.kəl/','paman','My uncle lives nearby.','Paman saya tinggal dekat sini.','🏠'],
  ['Family',11,'Cousin','/ˈkʌz.ən/','sepupu','My cousin is the same age as me.','Sepupu saya seumuran dengan saya.','🧑'],
  ['Family',12,'Child','/tʃaɪld/','anak','Their child is five years old.','Anak mereka berusia lima tahun.','🧒'],
  ['Food',1,'Rice','/raɪs/','nasi','We eat rice for lunch.','Kami makan nasi untuk makan siang.','🍚'],
  ['Food',2,'Bread','/bred/','roti','This bread is fresh.','Roti ini segar.','🍞'],
  ['Food',3,'Vegetable','/ˈvedʒ.tə.bəl/','sayuran','Carrots are vegetables.','Wortel adalah sayuran.','🥕'],
  ['Food',4,'Fruit','/fruːt/','buah','Mango is my favorite fruit.','Mangga adalah buah favorit saya.','🥭'],
  ['Food',5,'Chicken','/ˈtʃɪk.ɪn/','ayam','I ordered grilled chicken.','Saya memesan ayam panggang.','🍗'],
  ['Food',6,'Fish','/fɪʃ/','ikan','The fish is spicy.','Ikan ini pedas.','🐟'],
  ['Food',7,'Soup','/suːp/','sup','The soup is still hot.','Supnya masih panas.','🍲'],
  ['Food',8,'Breakfast','/ˈbrek.fəst/','sarapan','Breakfast starts at seven.','Sarapan dimulai pukul tujuh.','🥣'],
  ['Food',9,'Lunch','/lʌntʃ/','makan siang','Let’s have lunch together.','Ayo makan siang bersama.','🍱'],
  ['Food',10,'Dinner','/ˈdɪn.ər/','makan malam','Dinner is ready.','Makan malam sudah siap.','🍽️'],
  ['Travel',1,'Passport','/ˈpɑːs.pɔːt/','paspor','Please keep your passport with you.','Harap simpan paspormu bersamamu.','🛂'],
  ['Travel',2,'Ticket','/ˈtɪk.ɪt/','tiket','I booked my ticket online.','Saya memesan tiket secara daring.','🎫'],
  ['Travel',3,'Airport','/ˈeə.pɔːt/','bandara','We arrived at the airport early.','Kami tiba di bandara lebih awal.','🛫'],
  ['Travel',4,'Luggage','/ˈlʌɡ.ɪdʒ/','bagasi','My luggage is quite heavy.','Bagasi saya cukup berat.','🧳'],
  ['Travel',5,'Boarding pass','/ˈbɔː.dɪŋ pɑːs/','kartu naik pesawat','May I see your boarding pass?','Boleh saya lihat kartu naik pesawat Anda?','📱'],
  ['Travel',6,'Gate','/ɡeɪt/','gerbang keberangkatan','Our flight leaves from gate twelve.','Penerbangan kami berangkat dari gerbang dua belas.','🚪'],
  ['Travel',7,'Flight','/flaɪt/','penerbangan','The flight has been delayed.','Penerbangannya mengalami keterlambatan.','✈️'],
  ['Travel',8,'Hotel','/həʊˈtel/','hotel','Our hotel is near the beach.','Hotel kami dekat pantai.','🏨'],
  ['Travel',9,'Reservation','/ˌrez.əˈveɪ.ʃən/','reservasi','I have a reservation under Rina.','Saya punya reservasi atas nama Rina.','🛎️'],
  ['Travel',10,'Directions','/dəˈrek.ʃənz/','petunjuk arah','Could you give me directions to the station?','Bisakah Anda memberi petunjuk arah ke stasiun?','🧭'],
  ['Travel',11,'Station','/ˈsteɪ.ʃən/','stasiun','The station is across the road.','Stasiunnya berada di seberang jalan.','🚉'],
  ['Travel',12,'Destination','/ˌdes.tɪˈneɪ.ʃən/','tujuan','Bali is our final destination.','Bali adalah tujuan akhir kami.','📍'],
  ['Work & Business',1,'Colleague','/ˈkɒl.iːɡ/','rekan kerja','My colleague helped with the report.','Rekan kerja saya membantu laporan itu.','🧑‍💻'],
  ['Work & Business',2,'Deadline','/ˈded.laɪn/','tenggat waktu','The deadline is Friday afternoon.','Tenggat waktunya Jumat sore.','⏳'],
  ['Work & Business',3,'Meeting','/ˈmiː.tɪŋ/','rapat','The meeting starts at ten.','Rapat dimulai pukul sepuluh.','🗓️'],
  ['Work & Business',4,'Schedule','/ˈʃed.juːl/','jadwal','Let me check my schedule first.','Izinkan saya memeriksa jadwal terlebih dahulu.','📅'],
  ['Work & Business',5,'Project','/ˈprɒdʒ.ekt/','proyek','Our project is making good progress.','Proyek kami mengalami kemajuan yang baik.','📋'],
  ['Work & Business',6,'Client','/ˈklaɪ.ənt/','klien','The client approved our proposal.','Klien menyetujui proposal kami.','🤝'],
  ['Work & Business',7,'Report','/rɪˈpɔːt/','laporan','I will send the report today.','Saya akan mengirim laporan hari ini.','📄'],
  ['Work & Business',8,'Feedback','/ˈfiːd.bæk/','umpan balik','Thank you for your helpful feedback.','Terima kasih atas umpan balik yang membantu.','💬'],
  ['Work & Business',9,'Budget','/ˈbʌdʒ.ɪt/','anggaran','We need to review the budget.','Kita perlu meninjau anggaran.','💰'],
  ['Work & Business',10,'Presentation','/ˌprez.ənˈteɪ.ʃən/','presentasi','Her presentation was clear and concise.','Presentasinya jelas dan ringkas.','📊'],
  ['Work & Business',11,'Negotiate','/nɪˈɡəʊ.ʃi.eɪt/','bernegosiasi','They will negotiate the contract terms.','Mereka akan menegosiasikan ketentuan kontrak.','📝'],
  ['Work & Business',12,'Promotion','/prəˈməʊ.ʃən/','promosi jabatan','She earned a promotion this year.','Dia mendapat promosi jabatan tahun ini.','🚀'],
].map(args => lesson(...args));
